import { Equipment } from "./class";
export declare const hat_t7: Equipment;
export declare const gloves_t7: Equipment;
export declare const boots_t7: Equipment;
export declare const bag_t7: Equipment;
export declare const hairpin_t7: Equipment;
export declare const badge_t7: Equipment;
export declare const watch_t7: Equipment;
export declare const amulet_t7: Equipment;
export declare const necklace_t7: Equipment;
