name: 新功能
description: 您希望 ba-plugin 添加什么新功能
title: '[New Feature] '
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        感谢您贡献您的想法。请起一个能够清晰概括此功能的标题，便于开发者了解您的想法。

        ### 检查清单

        在提出建议之前，请先确认以下所有事项：

        1. 我已更新到最新版，确认我想要的功能还没有实现。
        2. 我已在 [Issues](https://github.com/Alin-sky/koishi-plugin-ba-plugin/issues?q=label%3Aenhancement) 中检索，确认这一类似的建议 **未被提交过**。
        3. 我认为我想要的功能是用户广泛需要的，且没有超出 **软件本来** 的开发目标。
        4. 我已知晓由于开发者时间精力有限，我提交的新功能请求可能需要比较久的时间才能实现。

  - type: checkboxes
    id: checklist
    attributes:
      label: 确认检查清单
      description: 在反馈此问题之前，请先确认一下事项是否满足：
      options:
        - label: |
            我已阅读以上清单并确认。
          required: true

  - type: textarea
    id: feature-new-content
    attributes:
      label: 您认为 ba-plugin 需要添加什么新功能/改进
      description: 您需要的新功能/改进
    validations:
      required: true

  - type: checkboxes
    id: revision
    attributes:
      label: 最后一步
      description: 回顾您的回答
      options:
        - label: 我认为上述的描述已经足以详细，以允许开发人员能准确理解。如果我的 Issue 没有按照上述的要求填写，可能会被 **无条件关闭**。
          required: true
